name: Build and Push Docker Images

on:
  push:
    on:
      branches:
        - main
        - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.io/insightfinderinc/mcp-server

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Generate timestamp tag
        id: timestamp
        run: echo "TAG=$(date +'%y%m%d%H%M')-${{ steps.branch.outputs.BRANCH }}" >> $GITHUB_OUTPUT

      - name: Print generated tag
        run: echo "Generated Docker tag:${{ steps.timestamp.outputs.TAG }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push leader Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:${{ steps.branch.outputs.BRANCH }}
